### ISSUE TITLE
Certain Judgment files have incorrect vertical frame naming

### ISSUE THREAD

**Issue by JoseVarelaP** [Tiny-Foxes/Judge#1]
In specific, the following files should be 2x6 instead of 2x7 (As they're not ECFA judgments).

- [CookingITG_A [double] (doubleres) 2x7.png](https://github.com/Tiny-Foxes/Judge/blob/master/Judgments/CookingITG_A%20%5Bdouble%5D%20(doubleres)%202x7.png)
- [Judgment CookingITG_B [double] (doubleres) 2x7.png](https://github.com/Tiny-Foxes/Judge/blob/master/Judgments/Judgment%20CookingITG_B%20%5Bdouble%5D%20(doubleres)%202x7.png)

**Comment by JapanYoshi** [comment]
Fixed in commit 8de26ce50d113850c0804ea316363f7d0edb42b2
